### ISSUE TITLE
install fails on Ubuntu 15.04

### ISSUE THREAD

**Issue by tmbdev** [roryk/clojupyter#1] opened 2015-06-18 02:08 UTC
I installed clojure-1.6 from Ubuntu and the "lein" script from Github. Finally, I cloned ipython-clojure and ran make. Somehow the leiningen dependency/classpath management isn't working. Note that it did download "jeromq-0.3.3.jar", so the package is there.

ipython-clojure$ ls
LICENSE.txt  Makefile  README.md  bin  doc  images  project.clj  src  test
ipython-clojure$ make
rm -f target/*.jar
lein uberjar
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Retrieving org/clojure/clojure/1.5.1/clojure-1.5.1.pom from central
Retrieving org/sonatype/oss/oss-parent/5/oss-parent-5.pom from central
Retrieving com/keminglabs/zmq-async/0.1.0/zmq-async-0.1.0.pom from clojars
Retrieving com/keminglabs/jzmq/a6c1706/jzmq-a6c1706.pom from clojars
Retrieving org/sonatype/oss/oss-parent/7/oss-parent-7.pom from central
Retrieving com/keminglabs/jzmq-osx64/a6c1706/jzmq-osx64-a6c1706.pom from clojars
Retrieving com/keminglabs/jzmq-linux64/a6c1706/jzmq-linux64-a6c1706.pom from clojars
Retrieving org/clojure/core.match/0.2.0/core.match-0.2.0.pom from central
Retrieving org/clojure/pom.contrib/0.1.2/pom.contrib-0.1.2.pom from central
Retrieving org/clojure/clojure/1.4.0/clojure-1.4.0.pom from central
Retrieving org/clojure/core.async/0.1.242.0-44b1e3-alpha/core.async-0.1.242.0-44b1e3-alpha.pom from central
Retrieving org/zeromq/jeromq/0.3.3/jeromq-0.3.3.pom from central
Retrieving cheshire/cheshire/5.3.1/cheshire-5.3.1.pom from clojars
Retrieving com/fasterxml/jackson/core/jackson-core/2.3.1/jackson-core-2.3.1.pom from central
Retrieving com/fasterxml/oss-parent/12/oss-parent-12.pom from central
Retrieving com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.3.1/jackson-dataformat-smile-2.3.1.pom from central
Retrieving tigris/tigris/0.1.1/tigris-0.1.1.pom from clojars
Retrieving clj-time/clj-time/0.7.0/clj-time-0.7.0.pom from clojars
Retrieving joda-time/joda-time/2.3/joda-time-2.3.pom from central
Retrieving org/clojure/clojure/1.6.0/clojure-1.6.0.pom from central
Retrieving org/zeromq/cljzmq/0.1.4/cljzmq-0.1.4.pom from central
Retrieving org/clojure/data.json/0.2.4/data.json-0.2.4.pom from central
Retrieving org/clojure/clojure/1.5.1/clojure-1.5.1.jar from central
Retrieving org/clojure/core.async/0.1.242.0-44b1e3-alpha/core.async-0.1.242.0-44b1e3-alpha.jar from central
Retrieving org/clojure/core.match/0.2.0/core.match-0.2.0.jar from central
Retrieving com/fasterxml/jackson/core/jackson-core/2.3.1/jackson-core-2.3.1.jar from central
Retrieving org/zeromq/jeromq/0.3.3/jeromq-0.3.3.jar from central
Retrieving com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.3.1/jackson-dataformat-smile-2.3.1.jar from central
Retrieving org/zeromq/cljzmq/0.1.4/cljzmq-0.1.4.jar from central
Retrieving joda-time/joda-time/2.3/joda-time-2.3.jar from central
Retrieving org/clojure/data.json/0.2.4/data.json-0.2.4.jar from central
Retrieving com/keminglabs/jzmq-osx64/a6c1706/jzmq-osx64-a6c1706.jar from clojars
Retrieving com/keminglabs/zmq-async/0.1.0/zmq-async-0.1.0.jar from clojars
Retrieving tigris/tigris/0.1.1/tigris-0.1.1.jar from clojars
Retrieving com/keminglabs/jzmq-linux64/a6c1706/jzmq-linux64-a6c1706.jar from clojars
Retrieving com/keminglabs/jzmq/a6c1706/jzmq-a6c1706.jar from clojars
Retrieving cheshire/cheshire/5.3.1/cheshire-5.3.1.jar from clojars
Retrieving clj-time/clj-time/0.7.0/clj-time-0.7.0.jar from clojars
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Compiling ipython-clojure.core
java.lang.ClassNotFoundException: org.jeromq.ZMQ, compiling:(core.clj:1:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3463)
	at clojure.lang.Compiler.compile1(Compiler.java:7153)
	at clojure.lang.Compiler.compile1(Compiler.java:7143)
	at clojure.lang.Compiler.compile(Compiler.java:7219)
	at clojure.lang.RT.compile(RT.java:398)
	at clojure.lang.RT.load(RT.java:438)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5336)
	at clojure.core$compile$fn__5023.invoke(core.clj:5541)
	at clojure.core$compile.invoke(core.clj:5540)
	at user$eval9$fn__16.invoke(form-init258825133935557999.clj:1)
	at user$eval9.invoke(form-init258825133935557999.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6609)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.main$load_script.invoke(main.clj:294)
	at clojure.main$init_opt.invoke(main.clj:299)
	at clojure.main$initialize.invoke(main.clj:327)
	at clojure.main$null_opt.invoke(main.clj:362)
	at clojure.main$main.doInvoke(main.clj:440)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: org.jeromq.ZMQ
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at ipython_clojure.core$loading__4910__auto__.invoke(core.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:159)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3458)
	... 28 more
Exception in thread "main" java.lang.ClassNotFoundException: org.jeromq.ZMQ, compiling:(core.clj:1:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3463)
	at clojure.lang.Compiler.compile1(Compiler.java:7153)
	at clojure.lang.Compiler.compile1(Compiler.java:7143)
	at clojure.lang.Compiler.compile(Compiler.java:7219)
	at clojure.lang.RT.compile(RT.java:398)
	at clojure.lang.RT.load(RT.java:438)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5336)
	at clojure.core$compile$fn__5023.invoke(core.clj:5541)
	at clojure.core$compile.invoke(core.clj:5540)
	at user$eval9$fn__16.invoke(form-init258825133935557999.clj:1)
	at user$eval9.invoke(form-init258825133935557999.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6609)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.main$load_script.invoke(main.clj:294)
	at clojure.main$init_opt.invoke(main.clj:299)
	at clojure.main$initialize.invoke(main.clj:327)
	at clojure.main$null_opt.invoke(main.clj:362)
	at clojure.main$main.doInvoke(main.clj:440)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: org.jeromq.ZMQ
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at ipython_clojure.core$loading__4910__auto__.invoke(core.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:159)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3458)
	... 28 more
Compilation failed: Subprocess failed
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
ipython-clojure$

**Comment by roryk** [comment] 2015-06-24 14:02
Hi @tmbdev,

Sorry for the delay in responding-- I haven't had a moment to debug this yet, but I will fix it soon.

**Comment by danielkarch** [comment] 2015-07-02 07:16
Hi,

I have the same problem.

**Comment by tmbdev** [comment] 2015-07-17 22:01
Changing org.jeromq to org.zeromq in core.clj fixes the compile error (the path seems to have changed).
However, the recommended way of adding the kernel isn't working.
When creating a kernelspec instead of the kernel.command works, until it gets an illegal character conversion deep inside Java after receiving a message.

**Comment by thomasjm** [comment] 2015-08-10 09:52
I'm seeing this too, it seems to be crashing on core.clj:76. Has anyone made any progress on this yet?

I'm wondering if it might be the IPython "signature" field that's causing this error, since that's the only field I can think of that might contain weird bytes...most everything else in an IPython message is JSON.

**Comment by roryk** [comment] 2015-08-10 17:26
Sorry, I haven't had a chance to dig into this yet, I will work on it tonight and see if I can reproduce and come up with a workaround, thanks for providing a good lead.

**Comment by roryk** [comment] 2015-08-13 04:02
Hi everyone,

Since jupyter (IPython 4.0) was released today, I started porting over to using that in a branch clojupyter.

**Comment by roryk** [comment] 2015-08-13 06:31
The *clojupyter* branch is partially functional for Jupyter kernel now. I'll update the documentation and rename the repository to that tomorrow.

**Comment by thomasjm** [comment] 2015-08-13 09:24
Thanks @roryk ! Looking forward to the update

**Comment by thomasjm** [comment] 2015-08-13 17:45
@roryk , this line in the makefile is failing for me:

```
sed 's|HOME|'${HOME}'|' resources/kernel.json > ~/.ipython/kernels/clojure/kernel.json;
```

Looks like `resources/kernel.json` isn't checked in

**Comment by roryk** [comment] 2015-08-13 17:48
Oop. Thanks, just pushed it.

**Comment by roryk** [comment] 2015-08-20 18:25
Thanks for the comments, looks like this is all set. Feel free to open up an issue if something isn't working. Thanks everyone!

**Closed by roryk** 2015-08-20 18:25 UTC
