### ISSUE TITLE
Immediate crash and restart

### ISSUE THREAD

**Issue by drewokane** [roryk/clojupyter#19] opened 2016-08-23 21:46 UTC
I am having trouble with the current `clojupyter` kernel where it will open a notebook fine but immediately crash and try to restart without success.

To reproduce:
```
conda create -n clojure jupyter notebook
source activate clojure
jupyter notebook
```
Then open up a new notebook and the error comes up. The stacktrace in the console looks like this:
```
(clojure) drew.okane:clojure/ $ jupyter notebook                                                                                                                                                [14:44:13]
[I 14:44:22.643 NotebookApp] Serving notebooks from local directory: /Users/drew.okane/Documents/clojure
[I 14:44:22.643 NotebookApp] 0 active kernels
[I 14:44:22.643 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 14:44:22.643 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 14:44:27.060 NotebookApp] Kernel started: 015a4264-597c-426f-8bc0-c57d91c9b693
Input configuration: {:transport tcp, :hb_port 51379, :kernel_name clojure, :ip 127.0.0.1, :control_port 51378, :key f4b43054-c133-4ac6-97ba-0994d4b181d8, :stdin_port 51377, :signature_scheme hmac-sha256, :shell_port 51375, :iopub_port 51376}
Connecting heartbeat to tcp://127.0.0.1:51379
Connecting shell to tcp://127.0.0.1:51375
Connecting iopub to tcp://127.0.0.1:51376
[W 14:44:37.118 NotebookApp] Timeout waiting for kernel_info reply from 015a4264-597c-426f-8bc0-c57d91c9b693
Message type comm_info_request not handled yet. Exiting.
Message dump: {:idents (), :delimiter <IDS|MSG>, :signature 39558a8fece06e3acf630c34b95dc43382d027b6bbafc26a6cec1093ccab9bdf, :header {:username username, :version 5.0, :msg_id 363BC734ACF6448B99CDFEE78A9EE02F, :msg_type comm_info_request, :session 3DDAE79CB74D4844830E43625E889D51}, :parent-header {}, :content {:target_name jupyter.widget}}
[I 14:44:39.061 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 015a4264-597c-426f-8bc0-c57d91c9b693 restarted
Input configuration: {:transport tcp, :hb_port 51379, :kernel_name clojure, :ip 127.0.0.1, :control_port 51378, :key f4b43054-c133-4ac6-97ba-0994d4b181d8, :stdin_port 51377, :signature_scheme hmac-sha256, :shell_port 51375, :iopub_port 51376}
Connecting heartbeat to tcp://127.0.0.1:51379
Connecting shell to tcp://127.0.0.1:51375
Connecting iopub to tcp://127.0.0.1:51376
```

**Comment by roryk** [comment] 2016-08-23 22:30
Hi @drewokane,

Sorry for the problem and thanks for posting a nice example. I think Jupyter 4.2.0 has a new message class which `comm_info_request` is one of them that we need to implement support for.  Are you running Jupyter 4.2.0+?

**Comment by roryk** [comment] 2016-08-23 22:32
That is the worst sentence I've ever written, yikes. Good thing my middle school English teacher is not on github.

**Comment by drewokane** [comment] 2016-08-23 22:41
@roryk strangely I have Jupyter 4.1.1, below is the full list:

```
╰─$ conda list
# packages in environment at /Users/drew.okane/anaconda/envs/clojure:
#
appnope                   0.1.0                    py27_0
backports.shutil_get_terminal_size 1.0.0                    py27_0    conda-forge
backports_abc             0.4                      py27_0    conda-forge
ca-certificates           2016.8.2                      3    conda-forge
certifi                   2016.8.2                 py27_0    conda-forge
configparser              3.5.0b2                  py27_0    conda-forge
decorator                 4.0.10                   py27_0    conda-forge
entrypoints               0.2.2                    py27_0    conda-forge
freetype                  2.6.3                         1    conda-forge
functools32               3.2.3.2                  py27_1    conda-forge
ipykernel                 4.3.1                    py27_1    conda-forge
ipython                   5.1.0                    py27_0    conda-forge
ipython_genutils          0.1.0                    py27_0    conda-forge
ipywidgets                5.2.2                    py27_0    conda-forge
jinja2                    2.8                      py27_1    conda-forge
jsonschema                2.5.1                    py27_0    conda-forge
jupyter_client            4.3.0                    py27_0    conda-forge
jupyter_console           5.0.0                    py27_0    conda-forge
jupyter_core              4.1.1                    py27_1    conda-forge
libpng                    1.6.24                        0    conda-forge
libsodium                 1.0.10                        0    conda-forge
markupsafe                0.23                     py27_0    conda-forge
mistune                   0.7.3                    py27_0    conda-forge
nbconvert                 4.2.0                    py27_0    conda-forge
nbformat                  4.0.1                    py27_0    conda-forge
ncurses                   5.9                           8    conda-forge
notebook                  4.2.2                    py27_0    conda-forge
openssl                   1.0.2h                        2    conda-forge
pathlib2                  2.1.0                    py27_0    conda-forge
pexpect                   4.2.0                    py27_1    conda-forge
pickleshare               0.7.3                    py27_0    conda-forge
pip                       8.1.2                    py27_0    conda-forge
prompt_toolkit            1.0.6                    py27_0    conda-forge
ptyprocess                0.5.1                    py27_0    conda-forge
pygments                  2.1.3                    py27_1    conda-forge
python                    2.7.12                        0    conda-forge
pyzmq                     15.4.0                   py27_0    conda-forge
qtconsole                 4.2.1                    py27_0    conda-forge
readline                  6.2                           0    conda-forge
setuptools                25.1.6                   py27_0    conda-forge
simplegeneric             0.8.1                    py27_0    conda-forge
singledispatch            3.4.0.3                  py27_0    conda-forge
sip                       4.18                     py27_0    conda-forge
six                       1.10.0                   py27_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
ssl_match_hostname        3.5.0.1                  py27_0    conda-forge
terminado                 0.6                      py27_0    conda-forge
tk                        8.5.19                        0    conda-forge
tornado                   4.4.1                    py27_1    conda-forge
traitlets                 4.2.2                    py27_0    conda-forge
wcwidth                   0.1.7                    py27_0    conda-forge
wheel                     0.29.0                   py27_0    conda-forge
widgetsnbextension        1.2.6                    py27_3    conda-forge
zeromq                    4.1.5                         0    conda-forge
zlib                      1.2.8                         3    conda-forge
jupyter                   1.0.0                    py27_3
pyqt                      4.11.4                   py27_4
python.app                1.2                      py27_4
qt                        4.8.7                         4
```

**Comment by roryk** [comment] 2016-08-23 23:41
Hmm-- I don't get it:

```
(clojure) rory@clotho:clojupyter (master)$ conda list | grep -e 'jupy\|ipy\|zmq'
ipykernel                 4.4.1                    py27_0
ipython                   5.1.0                    py27_0
ipython_genutils          0.1.0                    py27_0
ipywidgets                4.1.1                    py27_0
jupyter                   1.0.0                    py27_3
jupyter_client            4.3.0                    py27_0
jupyter_console           5.0.0                    py27_0
jupyter_core              4.1.1                    py27_0
pyzmq                     15.4.0                   py27_0
```

It looks like the only thing different is `ipykernel` which shouldn't matter. I downgraded and still see the same thing so that isn't it.

**Comment by drewokane** [comment] 2016-08-24 02:47
I decided to see if using the console interface made any difference and here's what I found.

The console interface works, *but*, it does give an error message:
```
─$ jupyter console --kernel clojure
Input configuration: {:transport tcp, :hb_port 61804, :kernel_name clojure, :ip 127.0.0.1, :control_port 61803, :key 9a788919-c9ab-4c4a-9a78-d63860e22aaf, :stdin_port 61802, :signature_scheme hmac-sha256, :shell_port 61800, :iopub_port 61801}
Connecting heartbeat to tcp://127.0.0.1:61804
Connecting shell to tcp://127.0.0.1:61800
Connecting iopub to tcp://127.0.0.1:61801
Jupyter console 5.0.0




In [1]: (+ 1 2)/Users/drew.okane/anaconda/envs/clojure/lib/python2.7/site-packages/jupyter_console/ptshell.py:571: UserWarning: The kernel did not respond to an is_complete_request. Setting `use_kernel_.
  warn('The kernel did not respond to an is_complete_request. '
In [1]: (+ 1 2)
Out[1]: 3

In [2]: (- 2 1)
      :
      :
Out[2]: 1

In [3]: (defn uniform-rand [a b] (let [width (- b a)] (+ a (* width (rand)))))
      :
      :
Out[3]: #'user/uniform-rand

In [4]: (uniform-rand 2 4)
      :
      :
Out[4]: 2.2166477377170852
```
For some reason after the first input, it takes two newlines before the kernel decides to execute the input. Not sure if this helps. I don't think I know enough to figure out what is going on with the kernel. :( I wish I knew more about this to help...

**Comment by roryk** [comment] 2016-08-24 02:54
Thanks-- the console is waiting for an empty line to signify the end of the input, to make it a little easier to write more complex code spanning lines.

**Comment by roryk** [comment] 2016-08-24 15:57
I think implementing support for the new messaging has to happen, I just don't get why I'm not seeing the error message but you all are.

**Comment by roryk** [comment] 2016-08-25 20:19
Would be sweet if someone else has this same issue, it is tough to test without getting the messages.

**Comment by roryk** [comment] 2016-08-28 16:29
Sorry Drew, I still can't get this error to happen. If I can figure out how, I will fix it.

**Comment by drewokane** [comment] 2016-08-28 18:32
Thanks! Sorry for the bother. Wish it were reproducible...

**Comment by hcarvalhoalves** [comment] 2016-09-06 02:16
I get the same warning w/ current `master` branch:

```
% jupyter-console --kernel=clojure
Jupyter Console 4.1.0
()
Input configuration: {:transport tcp, :hb_port 52045, :ip 127.0.0.1, :control_port 52044, :key a5dfcb27-8d9c-44da-9001-89245d1fcdd4, :stdin_port 52043, :signature_scheme hmac-sha256, :shell_port 52041, :iopub_port 52042}
Connecting heartbeat to tcp://127.0.0.1:52045
Connecting shell to tcp://127.0.0.1:52041
Connecting iopub to tcp://127.0.0.1:52042

In [1]: (+ 1 2)
WARNING: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.
Out[1]: 3
```

And if I hit <TAB> the kernel dies with:
```
In [2]: Message type complete_request not handled yet. Exiting.
Message dump: {:idents (), :delimiter <IDS|MSG>, :signature 407f6e1e927b18dcd777ccc89eca962a6ca4cd205d4823667eca0a79070a4937, :header {:username hcarvalhoalves, :msg_type complete_request, :msg_id 9386a9d6-7bf8-42b1-9a1a-0ed5c52fc6da, :version 5.0, :session e73a42c4-ec25-4245-b947-d5b9304d1701, :date 2016-09-05T23:14:01.771302}, :parent-header {}, :content {:code , :cursor_pos 0}}
```

My entire env:
```
% conda list
# packages in environment at /Users/hcarvalhoalves/anaconda:
#
Using Anaconda Cloud api site https://api.anaconda.org
abstract-rendering        0.5.1               np110py27_0
alabaster                 0.7.7                    py27_0
anaconda                  2.5.0               np110py27_0
anaconda-client           1.2.2                    py27_0
appnope                   0.1.0                    py27_0
appscript                 1.0.1                    py27_0
argcomplete               1.0.0                    py27_1
astropy                   1.1.1               np110py27_0
babel                     2.2.0                    py27_0
backports_abc             0.4                      py27_0
beautifulsoup4            4.4.1                    py27_0
bitarray                  0.8.1                    py27_0
blaze-core                0.9.0                    py27_0
bokeh                     0.11.0                   py27_0
boto                      2.39.0                   py27_0
bottleneck                1.0.0               np110py27_0
cdecimal                  2.3                      py27_0
cffi                      1.2.1                    py27_0
clyent                    1.2.0                    py27_0
colorama                  0.3.6                    py27_0
conda                     4.1.11                   py27_0
conda-build               1.19.0                   py27_0
conda-env                 2.5.2                    py27_0
configobj                 5.0.6                    py27_0
cryptography              1.0.2                    py27_0
curl                      7.45.0                        0
cycler                    0.9.0                    py27_0
cython                    0.23.4                   py27_1
cytoolz                   0.7.5                    py27_0
datashape                 0.5.0                    py27_0
decorator                 4.0.6                    py27_0
docutils                  0.12                     py27_0
dynd-python               0.7.1                    py27_0
enum34                    1.1.2                    py27_0
et_xmlfile                1.0.1                    py27_0
fastcache                 1.0.2                    py27_0
flask                     0.10.1                   py27_1
freetype                  2.5.5                         0
funcsigs                  0.4                      py27_0
futures                   3.0.3                    py27_0
gevent                    1.0.2                    py27_0
gevent-websocket          0.9.5                    py27_0
greenlet                  0.4.9                    py27_0
grin                      1.2.1                    py27_1
h5py                      2.5.0               np110py27_4
hdf5                      1.8.15.1                      2
idna                      2.0                      py27_0
ipaddress                 1.0.14                   py27_0
ipykernel                 4.2.2                    py27_0
ipython                   4.0.3                    py27_0
ipython-notebook          4.0.4                    py27_0
ipython-qtconsole         4.0.1                    py27_0
ipython_genutils          0.1.0                    py27_0
ipywidgets                4.1.1                    py27_0
itsdangerous              0.24                     py27_0
jbig                      2.1                           0
jdcal                     1.2                      py27_0
jedi                      0.9.0                    py27_0
jinja2                    2.8                      py27_0
jpeg                      8d                            1
jsonschema                2.4.0                    py27_0
jupyter                   1.0.0                    py27_1
jupyter_client            4.1.1                    py27_0
jupyter_console           4.1.0                    py27_0
jupyter_core              4.0.6                    py27_0
launcher                  1.0.0                         3
libdynd                   0.7.1                         0
libpng                    1.6.17                        0
libtiff                   4.0.6                         1
libxml2                   2.9.2                         0
libxslt                   1.1.28                        2
llvmlite                  0.8.0                    py27_0
lxml                      3.5.0                    py27_0
markupsafe                0.23                     py27_0
matplotlib                1.5.1               np110py27_0
opencv                    2.4.11                   py27_1    menpo
tbb                       4.3_20141023                  0    menpo
mistune                   0.7.1                    py27_0
mkl                       11.3.1                        0
mkl-service               1.1.2                    py27_0
multipledispatch          0.4.8                    py27_0
nbconvert                 4.1.0                    py27_0
nbformat                  4.0.1                    py27_0
networkx                  1.11                     py27_0
nltk                      3.1                      py27_0
node-webkit               0.10.1                        0
nose                      1.3.7                    py27_0
notebook                  4.1.0                    py27_0
numba                     0.23.1              np110py27_0
numexpr                   2.4.6               np110py27_1
numpy                     1.10.4                   py27_0
odo                       0.4.0                    py27_0
openpyxl                  2.3.2                    py27_0
openssl                   1.0.2h                        2
pandas                    0.17.1              np110py27_0
path.py                   8.1.2                    py27_1
patsy                     0.4.0               np110py27_0
pep8                      1.7.0                    py27_0
pexpect                   3.3                      py27_0
pickleshare               0.5                      py27_0
pillow                    3.1.0                    py27_0
pip                       8.1.2                    py27_0
ply                       3.8                      py27_0
psutil                    3.4.2                    py27_0
ptyprocess                0.5                      py27_0
py                        1.4.31                   py27_0
pyasn1                    0.1.9                    py27_0
pyaudio                   0.2.7                    py27_0
pycosat                   0.6.1                    py27_1
pycparser                 2.14                     py27_0
pycrypto                  2.6.1                    py27_0
pycurl                    7.19.5.3                 py27_0
pyflakes                  1.0.0                    py27_0
pygments                  2.1                      py27_0
pyopenssl                 0.15.1                   py27_1
pyparsing                 2.0.3                    py27_0
pyqt                      4.11.4                   py27_1
pytables                  3.2.2               np110py27_0
pytest                    2.8.5                    py27_0
python                    2.7.12                        1
python-dateutil           2.4.2                    py27_0
python.app                1.2                      py27_4
pytz                      2015.7                   py27_0
pyyaml                    3.11                     py27_4
pyzmq                     15.2.0                   py27_0
qt                        4.8.7                         1
qtconsole                 4.1.1                    py27_0
readline                  6.2                           2
redis                     2.6.9                         0
redis-py                  2.10.3                   py27_0
requests                  2.11.1                   py27_0
rope                      0.9.4                    py27_1
ruamel_yaml               0.11.14                  py27_0
scikit-image              0.11.3              np110py27_0
scikit-learn              0.17                np110py27_2
scipy                     0.17.0              np110py27_0
setuptools                26.1.1                   py27_0
simplegeneric             0.8.1                    py27_0
singledispatch            3.4.0.3                  py27_0
sip                       4.16.9                   py27_0
six                       1.10.0                   py27_0
snowballstemmer           1.2.1                    py27_0
sockjs-tornado            1.0.1                    py27_0
sphinx                    1.3.5                    py27_0
sphinx_rtd_theme          0.1.9                    py27_0
spyder                    2.3.8                    py27_0
spyder-app                2.3.8                    py27_0
sqlalchemy                1.0.11                   py27_0
sqlite                    3.13.0                        0
ssl_match_hostname        3.4.0.2                  py27_0
statsmodels               0.6.1               np110py27_0
sympy                     0.7.6.1                  py27_0
terminado                 0.5                      py27_1
tk                        8.5.18                        0
toolz                     0.7.4                    py27_0
tornado                   4.3                      py27_0
traitlets                 4.1.0                    py27_0
unicodecsv                0.14.1                   py27_0
werkzeug                  0.11.3                   py27_0
wheel                     0.29.0                   py27_0
xlrd                      0.9.4                    py27_0
xlsxwriter                0.8.4                    py27_0
xlwings                   0.6.4                    py27_0
xlwt                      1.0.0                    py27_0
xz                        5.0.5                         0
yaml                      0.1.6                         0
zeromq                    4.1.3                         0
zlib                      1.2.8                         3
```

All dependencies used on `make`:
```
% make
lein uberjar
Retrieving org/clojure/clojure/1.8.0/clojure-1.8.0.pom from central
Retrieving org/zeromq/jeromq/0.3.4/jeromq-0.3.4.pom from central
Retrieving cheshire/cheshire/5.5.0/cheshire-5.5.0.pom from clojars
Retrieving com/fasterxml/jackson/core/jackson-core/2.5.3/jackson-core-2.5.3.pom from central
Retrieving com/fasterxml/jackson/jackson-parent/2.5.1/jackson-parent-2.5.1.pom from central
Retrieving com/fasterxml/oss-parent/19/oss-parent-19.pom from central
Retrieving com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.5.3/jackson-dataformat-smile-2.5.3.pom from central
Retrieving com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.5.3/jackson-dataformat-cbor-2.5.3.pom from central
Retrieving pandect/pandect/0.5.4/pandect-0.5.4.pom from clojars
Retrieving potemkin/potemkin/0.4.1/potemkin-0.4.1.pom from clojars
Retrieving riddley/riddley/0.1.10/riddley-0.1.10.pom from clojars
Retrieving org/bouncycastle/bcprov-jdk15on/1.52/bcprov-jdk15on-1.52.pom from central
Retrieving org/zeromq/cljzmq/0.1.4/cljzmq-0.1.4.pom from central
Retrieving org/clojure/data.json/0.2.6/data.json-0.2.6.pom from central
Retrieving com/cemerick/pomegranate/0.3.0/pomegranate-0.3.0.pom from central
Retrieving org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.pom from central
Retrieving org/sonatype/aether/aether/1.13.1/aether-1.13.1.pom from central
Retrieving org/sonatype/forge/forge-parent/10/forge-parent-10.pom from central
Retrieving org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.pom from central
Retrieving org/sonatype/aether/aether-impl/1.13.1/aether-impl-1.13.1.pom from central
Retrieving org/sonatype/aether/aether-spi/1.13.1/aether-spi-1.13.1.pom from central
Retrieving org/sonatype/aether/aether-connector-file/1.13.1/aether-connector-file-1.13.1.pom from central
Retrieving org/sonatype/aether/aether-connector-wagon/1.13.1/aether-connector-wagon-1.13.1.pom from central
Retrieving org/apache/maven/wagon/wagon-provider-api/1.0-beta-6/wagon-provider-api-1.0-beta-6.pom from central
Retrieving org/apache/maven/wagon/wagon/1.0-beta-6/wagon-1.0-beta-6.pom from central
Retrieving org/apache/maven/maven-parent/11/maven-parent-11.pom from central
Retrieving org/apache/apache/5/apache-5.pom from central
Retrieving org/codehaus/plexus/plexus-classworlds/2.4/plexus-classworlds-2.4.pom from central
Retrieving org/codehaus/plexus/plexus/2.0.7/plexus-2.0.7.pom from central
Retrieving org/sonatype/sisu/sisu-inject-plexus/2.2.3/sisu-inject-plexus-2.2.3.pom from central
Retrieving org/sonatype/sisu/inject/guice-plexus/2.2.3/guice-plexus-2.2.3.pom from central
Retrieving org/sonatype/sisu/inject/guice-bean/2.2.3/guice-bean-2.2.3.pom from central
Retrieving org/sonatype/sisu/inject/containers/2.2.3/containers-2.2.3.pom from central
Retrieving org/sonatype/sisu/sisu-inject/2.2.3/sisu-inject-2.2.3.pom from central
Retrieving org/sonatype/sisu/sisu-parent/2.2.3/sisu-parent-2.2.3.pom from central
Retrieving org/sonatype/forge/forge-parent/9/forge-parent-9.pom from central
Retrieving org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.pom from central
Retrieving org/codehaus/plexus/plexus-containers/1.5.5/plexus-containers-1.5.5.pom from central
Retrieving org/sonatype/sisu/sisu-inject-bean/2.2.3/sisu-inject-bean-2.2.3.pom from central
Retrieving org/sonatype/sisu/sisu-guice/3.0.3/sisu-guice-3.0.3.pom from central
Retrieving org/sonatype/sisu/inject/guice-parent/3.0.3/guice-parent-3.0.3.pom from central
Retrieving org/apache/maven/maven-aether-provider/3.0.4/maven-aether-provider-3.0.4.pom from central
Retrieving org/apache/maven/maven/3.0.4/maven-3.0.4.pom from central
Retrieving org/apache/maven/maven-parent/21/maven-parent-21.pom from central
Retrieving org/apache/apache/10/apache-10.pom from central
Retrieving org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.pom from central
Retrieving org/codehaus/plexus/plexus-utils/2.0.6/plexus-utils-2.0.6.pom from central
Retrieving org/apache/maven/maven-model-builder/3.0.4/maven-model-builder-3.0.4.pom from central
Retrieving org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.pom from central
Retrieving org/codehaus/plexus/plexus-components/1.1.18/plexus-components-1.1.18.pom from central
Retrieving org/apache/maven/maven-repository-metadata/3.0.4/maven-repository-metadata-3.0.4.pom from central
Retrieving org/apache/maven/wagon/wagon-provider-api/2.2/wagon-provider-api-2.2.pom from central
Retrieving org/apache/maven/wagon/wagon/2.2/wagon-2.2.pom from central
Retrieving org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.pom from central
Retrieving org/sonatype/spice/spice-parent/16/spice-parent-16.pom from central
Retrieving org/sonatype/forge/forge-parent/5/forge-parent-5.pom from central
Retrieving org/apache/maven/wagon/wagon-http/2.2/wagon-http-2.2.pom from central
Retrieving org/apache/maven/wagon/wagon-providers/2.2/wagon-providers-2.2.pom from central
Retrieving org/apache/maven/wagon/wagon-http-shared4/2.2/wagon-http-shared4-2.2.pom from central
Retrieving org/jsoup/jsoup/1.6.1/jsoup-1.6.1.pom from central
Retrieving commons-io/commons-io/2.0.1/commons-io-2.0.1.pom from central
Retrieving org/apache/commons/commons-parent/15/commons-parent-15.pom from central
Retrieving org/apache/apache/7/apache-7.pom from central
Retrieving mvxcvi/puget/1.0.0/puget-1.0.0.pom from clojars
Retrieving fipp/fipp/0.6.3/fipp-0.6.3.pom from clojars
Retrieving org/clojure/clojure/1.7.0-beta2/clojure-1.7.0-beta2.pom from central
Retrieving org/clojure/core.rrb-vector/0.0.11/core.rrb-vector-0.0.11.pom from central
Retrieving mvxcvi/arrangement/1.0.0/arrangement-1.0.0.pom from clojars
Retrieving fipp/fipp/0.6.4/fipp-0.6.4.pom from clojars
Retrieving org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.pom from central
Retrieving org/clojure/clojure/1.8.0/clojure-1.8.0.jar from central
Retrieving com/fasterxml/jackson/core/jackson-core/2.5.3/jackson-core-2.5.3.jar from central
Retrieving com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.5.3/jackson-dataformat-smile-2.5.3.jar from central
Retrieving org/zeromq/jeromq/0.3.4/jeromq-0.3.4.jar from central
Retrieving com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.5.3/jackson-dataformat-cbor-2.5.3.jar from central
Retrieving org/bouncycastle/bcprov-jdk15on/1.52/bcprov-jdk15on-1.52.jar from central
Retrieving org/clojure/data.json/0.2.6/data.json-0.2.6.jar from central
Retrieving com/cemerick/pomegranate/0.3.0/pomegranate-0.3.0.jar from central
Retrieving org/zeromq/cljzmq/0.1.4/cljzmq-0.1.4.jar from central
Retrieving org/sonatype/aether/aether-impl/1.13.1/aether-impl-1.13.1.jar from central
Retrieving org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.jar from central
Retrieving org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar from central
Retrieving org/sonatype/aether/aether-spi/1.13.1/aether-spi-1.13.1.jar from central
Retrieving org/sonatype/aether/aether-connector-file/1.13.1/aether-connector-file-1.13.1.jar from central
Retrieving org/sonatype/aether/aether-connector-wagon/1.13.1/aether-connector-wagon-1.13.1.jar from central
Retrieving org/codehaus/plexus/plexus-classworlds/2.4/plexus-classworlds-2.4.jar from central
Retrieving org/sonatype/sisu/sisu-inject-plexus/2.2.3/sisu-inject-plexus-2.2.3.jar from central
Retrieving org/sonatype/sisu/sisu-inject-bean/2.2.3/sisu-inject-bean-2.2.3.jar from central
Retrieving org/sonatype/sisu/sisu-guice/3.0.3/sisu-guice-3.0.3-no_aop.jar from central
Retrieving org/apache/maven/maven-aether-provider/3.0.4/maven-aether-provider-3.0.4.jar from central
Retrieving org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.jar from central
Retrieving org/apache/maven/maven-model-builder/3.0.4/maven-model-builder-3.0.4.jar from central
Retrieving org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar from central
Retrieving org/apache/maven/maven-repository-metadata/3.0.4/maven-repository-metadata-3.0.4.jar from central
Retrieving org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar from central
Retrieving org/codehaus/plexus/plexus-utils/2.0.6/plexus-utils-2.0.6.jar from central
Retrieving org/apache/maven/wagon/wagon-provider-api/2.2/wagon-provider-api-2.2.jar from central
Retrieving org/apache/maven/wagon/wagon-http/2.2/wagon-http-2.2.jar from central
Retrieving org/apache/maven/wagon/wagon-http-shared4/2.2/wagon-http-shared4-2.2.jar from central
Retrieving org/jsoup/jsoup/1.6.1/jsoup-1.6.1.jar from central
Retrieving commons-io/commons-io/2.0.1/commons-io-2.0.1.jar from central
Retrieving org/clojure/core.rrb-vector/0.0.11/core.rrb-vector-0.0.11.jar from central
Retrieving org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.jar from central
Retrieving cheshire/cheshire/5.5.0/cheshire-5.5.0.jar from clojars
Retrieving tigris/tigris/0.1.1/tigris-0.1.1.jar from clojars
Retrieving riddley/riddley/0.1.10/riddley-0.1.10.jar from clojars
Retrieving pandect/pandect/0.5.4/pandect-0.5.4.jar from clojars
Retrieving potemkin/potemkin/0.4.1/potemkin-0.4.1.jar from clojars
Retrieving mvxcvi/puget/1.0.0/puget-1.0.0.jar from clojars
Retrieving mvxcvi/arrangement/1.0.0/arrangement-1.0.0.jar from clojars
Retrieving fipp/fipp/0.6.4/fipp-0.6.4.jar from clojars
Compiling clojupyter.core
Compiling clojupyter.core
Created /Users/hcarvalhoalves/Projetos/clojupyter/target/clojupyter-0.1.0-SNAPSHOT.jar
Created /Users/hcarvalhoalves/Projetos/clojupyter/target/clojupyter-0.1.0-SNAPSHOT-standalone.jar
cat bin/clojupyter.template $(find . -maxdepth 2 -type f | grep -e ".*standalone.*\.jar") > bin/clojupyter
chmod +x bin/clojupyter
```

I guess that's enough info to reproduce.

**Comment by roryk** [comment] 2016-09-06 13:09
Thanks! I can definitely reproduce that error-- clojupyter doesn't support autocompletion yet and we're not handling the request properly, I'll fix that bug tonight.

**Comment by roryk** [comment] 2016-09-07 01:22
Ah, it will take more than a night to fix. We need to implement checking to see if a form is complete which will handle the warning, and then implement code completion, which will handle the crash on TAB.

**Comment by roryk** [comment] 2016-09-07 02:33
Ok, upgrading to jupyter_console 5.0.0 fixes the hang-on-autocomplete: https://github.com/jupyter/jupyter_console/pull/47

**Comment by roryk** [comment] 2016-09-07 03:05
Spoke too soon, still crashes on null input and after auto-completion. Will have to implement a real fix.

**Comment by roryk** [comment] 2016-09-12 14:08
Hopefully the original issue should be fixed now that we do checking for complete code blocks properly. This introduced another issue of not handling exceptions properly which still needs to get fixed though.

**Closed by roryk** 2016-09-12 14:08 UTC

**Comment by hcarvalhoalves** [comment] 2016-09-12 18:29
Cool, thanks @roryk , I'll take a look at it later.
